2018/12/27 20:56:30 - __main__ - INFO - 15 - do_logging - This is a log info
2018/12/27 20:56:30 - __main__ - DEBUG - 16 - do_logging - Debugging
2018/12/27 20:56:30 - __main__ - WARNING - 17 - do_logging - Warning exists
2018/12/27 20:56:30 - __main__ - INFO - 18 - do_logging - Finish
2018-12-27 21:05:32,510 - __main__ - INFO - This is a log info
2018-12-27 21:05:32,510 - __main__ - WARNING - Warning exists
2018-12-27 21:05:32,510 - __main__ - INFO - Finish
2018-12-28 10:30:41,977 - __main__ - INFO - This is a log info
2018-12-28 10:30:48,871 - __main__ - DEBUG - Debugging
2018-12-28 10:30:51,128 - __main__ - WARNING - Warning exists
2018-12-28 10:30:53,385 - __main__ - INFO - Finish
2018-12-28 10:33:16,991 - __main__ - INFO - This is a log info
2018-12-28 10:33:23,841 - __main__ - DEBUG - Debugging
2018-12-28 10:33:26,098 - __main__ - WARNING - Warning exists
2018-12-28 10:33:28,353 - __main__ - INFO - Finish
2018-12-28 10:33:30,608 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "E:/Mannix/logging 模块/do_Handler.py", line 34, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2018-12-28 10:33:40,342 - __main__ - INFO - This is a log info
2018-12-28 10:33:40,342 - __main__ - DEBUG - Debugging
2018-12-28 10:33:40,342 - __main__ - WARNING - Warning exists
2018-12-28 10:33:40,342 - __main__ - INFO - Finish
2018-12-28 10:33:40,342 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "E:/Mannix/logging 模块/do_Handler.py", line 34, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2018-12-28 10:40:29,827 - __main__ - INFO - This is a log info
2018-12-28 10:40:29,827 - __main__ - DEBUG - Debugging
2018-12-28 10:40:29,827 - __main__ - WARNING - Warning exists
2018-12-28 10:40:29,827 - __main__ - INFO - Finish
2018-12-28 10:40:29,827 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "E:/Mannix/logging 模块/do_Handler.py", line 34, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2018-12-28 14:31:22,218 - __main__ - INFO - This is a log info
2018-12-28 14:31:22,219 - __main__ - DEBUG - Debugging
2018-12-28 14:31:22,219 - __main__ - WARNING - Warning exists
2018-12-28 14:31:22,219 - __main__ - INFO - Finish
2018-12-28 14:31:22,219 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "E:/Mannix/logging 模块/do_Handler.py", line 34, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
